# Generated by Django 4.0.4 on 2022-05-20 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apothecary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10)),
                ('address', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('fabricator', models.TextField(blank=True, verbose_name='Fabricator')),
                ('type', models.CharField(choices=[('PL', 'PILLS'), ('CP', 'CAPSULES'), ('PW', 'POWDERS'), ('SR', 'SYRUP'), ('MX', 'MIXTURE'), ('ON', 'OINTMENT')], default='PL', max_length=2, verbose_name='Type')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Image')),
                ('min_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Min price')),
                ('max_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Max price')),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('apothecary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.apothecary')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('amount', models.PositiveIntegerField(verbose_name='Amount')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.medicine')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pharmacy')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('amount', models.PositiveIntegerField(verbose_name='Amount')),
                ('status', models.CharField(choices=[('AC', 'ACTIVE'), ('DN', 'DONE'), ('CN', 'CANCELED')], default='AC', max_length=2, verbose_name='Status')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pharmacy')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
        ),
    ]
