# Generated by Django 4.0.4 on 2022-05-19 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_remove_client_email_remove_client_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='max_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Max price'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='min_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Min price'),
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
