# Generated by Django 4.0.4 on 2022-05-26 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_apothecary_about_education_apothecary_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='max_price',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='min_price',
        ),
    ]
