MEDICINE_TYPE_PILLS = "PILLS"
MEDICINE_TYPE_CAPSULES = "CAPSULES"
MEDICINE_TYPE_POWDERS = "POWDERS"
MEDICINE_TYPE_SYRUP = "SYRUP"
MEDICINE_TYPE_MIXTURE = "MIXTURE"
MEDICINE_TYPE_OINTMENT = "OINTMENT"

MEDICINE_TYPES = [(MEDICINE_TYPE_PILLS, MEDICINE_TYPE_PILLS),
                  (MEDICINE_TYPE_CAPSULES, MEDICINE_TYPE_CAPSULES),
                  (MEDICINE_TYPE_POWDERS, MEDICINE_TYPE_POWDERS),
                  (MEDICINE_TYPE_SYRUP, MEDICINE_TYPE_SYRUP),
                  (MEDICINE_TYPE_MIXTURE, MEDICINE_TYPE_MIXTURE),
                  (MEDICINE_TYPE_OINTMENT, MEDICINE_TYPE_OINTMENT)]

ORDER_STATUS_IN_CART = "IN CART"
ORDER_STATUS_ACTIVE = "ACTIVE"
ORDER_STATUS_DONE = "DONE"
ORDER_STATUS_CANCELED = "CANCELED"
ORDER_STATUS_DELETED = "DELETED"

ORDER_STATUSES = [(ORDER_STATUS_IN_CART, ORDER_STATUS_IN_CART),
                  (ORDER_STATUS_ACTIVE, ORDER_STATUS_ACTIVE),
                  (ORDER_STATUS_DONE, ORDER_STATUS_DONE),
                  (ORDER_STATUS_CANCELED, ORDER_STATUS_CANCELED),
                  (ORDER_STATUS_DELETED, ORDER_STATUS_DELETED)]
